[tools]
go = "latest"
node = "latest"
ruby = "latest"
rust = "latest"
bun = "latest"

[settings]
idiomatic_version_file_enable_tools = []

[env]
MISE_GO_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-go-packages"
MISE_RUBY_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-gems"
MISE_NODE_DEFAULT_PACKAGES_FILE = "{{env.HOME}}/.config/mise/default-nodejs-packages"
